begin;
select plan(36);
insert into auth.users(id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values('13000000-0000-4000-8000-000000000001','authenticated','authenticated','rates@test.local','',now(),'{}','{}',now(),now());
select set_config('request.jwt.claim.sub','13000000-0000-4000-8000-000000000001',true);
select set_config('request.jwt.claims','{"sub":"13000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
create temp table rate_hotel as select *, (now() at time zone 'Africa/Lagos')::date as today from public.setup_hotel('Rate tests','Rate property',null,3,1000000);
create temp table rate_rooms as select r.id,r.room_type_id,r.room_number from public.rooms r join rate_hotel h on h.property_id=r.property_id;
create temp table rate_periods(kind text primary key,id uuid);
create temp table rate_bookings(kind text primary key,id uuid);
create temp table rate_review(quote jsonb);
create temp table rate_other_property as select public.create_property(organization_id,'Other property',null,1,1000000) as id from rate_hotel;
create temp table rate_other_room as select r.id,r.room_type_id from public.rooms r join rate_other_property p on p.id=r.property_id;
grant select on rate_hotel,rate_rooms,rate_other_property,rate_other_room to authenticated;
grant select,insert on rate_periods,rate_bookings,rate_review to authenticated;
set local role authenticated;

select lives_ok($$insert into rate_periods select 'holiday',public.schedule_room_rate(r.room_type_id,'Holiday',h.today+10,h.today+12,2000000) from rate_hotel h,rate_rooms r where r.room_number='101'$$,'owner schedules a dated rate');
select throws_ok($$select public.schedule_room_rate(r.room_type_id,'Overlap',h.today+11,h.today+13,2500000) from rate_hotel h,rate_rooms r where r.room_number='101'$$,'23P01',null,'overlapping rate periods are rejected');
select lives_ok($$insert into rate_periods select 'festival',public.schedule_room_rate(r.room_type_id,'Festival',h.today+12,h.today+13,3000000) from rate_hotel h,rate_rooms r where r.room_number='101'$$,'adjacent exclusive-end periods are allowed');
select results_eq($$select q.standard_rate_kobo from rate_hotel h,rate_rooms r,lateral public.get_room_rate_quote(r.id,h.today+9,h.today+13) q where r.room_number='101' order by q.service_date$$,$$values (1000000::bigint),(2000000::bigint),(2000000::bigint),(3000000::bigint)$$,'quote prices every night across rate boundaries');
select is((select count(*)::int from rate_hotel h,rate_rooms r,lateral public.get_room_rate_quote(r.id,h.today+9,h.today+13) q where r.room_number='101'),4,'departure night is excluded');
insert into rate_review select jsonb_agg(jsonb_build_object('service_date',q.service_date,'standard_rate_kobo',q.standard_rate_kobo) order by q.service_date) from rate_hotel h,rate_rooms r,lateral public.get_room_rate_quote(r.id,h.today+9,h.today+13) q where r.room_number='101';
select lives_ok($$insert into rate_bookings select 'scheduled',public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Scheduled guest',null,null,h.today+9,h.today+13,1::smallint,null,null,null,v.quote) from rate_hotel h,rate_rooms r,rate_review v where r.room_number='101'$$,'reviewed scheduled quote can be booked');
select is((select sum(charged_rate_kobo)::bigint from public.reservation_night_rates where reservation_id=(select id from rate_bookings where kind='scheduled')),8000000::bigint,'saved booking total sums the nightly prices');
select lives_ok($$select public.set_room_base_rate(room_type_id,1500000,'Revised base pricing') from rate_rooms where room_number='101'$$,'owner updates the base rate');
select is((select sum(charged_rate_kobo)::bigint from public.reservation_night_rates where reservation_id=(select id from rate_bookings where kind='scheduled')),8000000::bigint,'base rate changes do not reprice existing bookings');
select lives_ok($$select public.retire_room_rate(id,'Season promotion ended') from rate_periods where kind='holiday'$$,'owner retires a dated rate');
select is((select sum(charged_rate_kobo)::bigint from public.reservation_night_rates where reservation_id=(select id from rate_bookings where kind='scheduled')),8000000::bigint,'retired rate does not reprice existing bookings');
select throws_ok($$select public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Stale review',null,null,h.today+9,h.today+13,1::smallint,null,null,null,v.quote) from rate_hotel h,rate_rooms r,rate_review v where r.room_number='102'$$,'23514',null,'a stale quote cannot be confirmed');
select is((select count(*)::int from public.reservations where guest_id in (select id from public.guests where full_name='Stale review')),0,'stale quote rejection leaves no partial booking');
select lives_ok($$insert into rate_periods select 'past',public.schedule_room_rate(r.room_type_id,'Past event',h.today-2,h.today-1,2500000) from rate_hotel h,rate_rooms r where r.room_number='101'$$,'past effective dates can be recorded for a late check-in');
select lives_ok($$insert into rate_bookings select 'posting',public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Posting guest',null,null,h.today-2,h.today+1,1::smallint,null) from rate_hotel h,rate_rooms r where r.room_number='101'$$,'mixed-rate in-house stay can be created');
select public.update_room_housekeeping_status(id,'clean') from rate_rooms where room_number='101';
select public.check_in_reservation(id) from rate_bookings where kind='posting';
select public.set_room_base_rate(room_type_id,3500000,'New future base price') from rate_rooms where room_number='101';
select is((select public.post_due_room_nights(id) from rate_bookings where kind='posting'),2,'two completed nights are posted');
select is((select sum(i.total_amount_kobo)::bigint from public.folio_items i join public.folios f on f.id=i.folio_id where f.reservation_id=(select id from rate_bookings where kind='posting')),4000000::bigint,'posting uses the saved per-night amounts after prices change');
select is((select public.post_due_room_nights(id) from rate_bookings where kind='posting'),0,'posting the same completed nights is idempotent');
select is((select count(*)::int from (select j.id from public.journals j join public.journal_lines l on l.journal_id=j.id where j.status='posted' and j.source_id=(select id from rate_bookings where kind='posting') group by j.id having sum(l.debit_kobo)<>sum(l.credit_kobo)) bad),0,'mixed nightly postings remain balanced');
select lives_ok($$insert into rate_bookings select 'discount',public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Approved discount',null,null,h.today+9,h.today+13,1::smallint,1000000,null,'Agreed four-night package') from rate_hotel h,rate_rooms r where r.room_number='102'$$,'manager can approve one fixed rate across a mixed-rate stay');
select is((select sum(charged_rate_kobo)::bigint from public.reservation_night_rates where reservation_id=(select id from rate_bookings where kind='discount')),4000000::bigint,'approved fixed rate is saved for every night');

reset role;
select throws_ok($$update public.reservation_night_rates set charged_rate_kobo=1 where reservation_id=(select id from rate_bookings where kind='scheduled')$$,'23514',null,'saved nightly prices reject edits even with database table privileges');
select throws_ok($$delete from public.reservation_night_rates where reservation_id=(select id from rate_bookings where kind='scheduled')$$,'23514',null,'saved nightly prices reject deletion');
set local role authenticated;
insert into rate_periods select 'zero',public.schedule_room_rate(r.room_type_id,'Complimentary event',h.today+30,h.today+31,0) from rate_hotel h,rate_rooms r where r.room_number='101';
select lives_ok($$insert into rate_bookings select 'zero',public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Complimentary event guest',null,null,h.today+30,h.today+31,1::smallint,null,null,'Approved hosted event') from rate_hotel h,rate_rooms r where r.room_number='103'$$,'owner may approve a zero scheduled rate with a reason');
select is((select after_data->>'complimentary' from public.audit_events where entity_id=(select id from rate_bookings where kind='zero') and action='reservation_pricing_approved'),'true','zero scheduled rate approval is explicitly audited as complimentary');
insert into rate_periods select 'other',public.schedule_room_rate(room_type_id,'Other hotel event',current_date+10,current_date+12,2000000) from rate_other_room;
insert into rate_bookings select 'other',public.create_priced_reservation(h.organization_id,p.id,r.id,'Other property guest',null,null,current_date+10,current_date+12,1::smallint,null) from rate_hotel h,rate_other_property p,rate_other_room r;
reset role;
update public.organization_memberships set role='front_desk',all_properties=false where user_id='13000000-0000-4000-8000-000000000001';
insert into public.membership_properties(organization_id,user_id,property_id) select organization_id,'13000000-0000-4000-8000-000000000001',property_id from rate_hotel;
set local role authenticated;
select throws_ok($$select public.set_room_base_rate(room_type_id,1000000,'Unauthorized change') from rate_rooms where room_number='101'$$,'42501',null,'front desk cannot change base rates');
select throws_ok($$select public.schedule_room_rate(r.room_type_id,'Unauthorized',h.today+40,h.today+41,1000000) from rate_hotel h,rate_rooms r where r.room_number='101'$$,'42501',null,'front desk cannot schedule rates');
select throws_ok($$select public.retire_room_rate(id,'Unauthorized retirement') from rate_periods where kind='festival'$$,'42501',null,'front desk cannot retire rates');
select lives_ok($$insert into rate_bookings select 'frontdesk',public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Standard front desk',null,null,h.today+12,h.today+14,1::smallint,null) from rate_hotel h,rate_rooms r where r.room_number='103'$$,'front desk can book scheduled prices without an override');
select throws_ok($$select public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Flat bypass',null,null,h.today+12,h.today+14,1::smallint,3500000) from rate_hotel h,rate_rooms r where r.room_number='102'$$,'42501',null,'front desk cannot replace a mixed nightly quote with the base price');
select throws_ok($$select public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Zero event guest',null,null,h.today+30,h.today+31,1::smallint,null) from rate_hotel h,rate_rooms r where r.room_number='101'$$,'42501',null,'zero scheduled nights still require managerial approval');
select throws_ok($$select q.* from rate_other_room r cross join lateral public.get_room_rate_quote(r.id,current_date+20,current_date+21) q$$,'42501',null,'rate quote rejects an unassigned property');
select is((select count(*)::int from public.room_rate_periods where property_id=(select id from rate_other_property)),0,'rate period RLS hides unassigned properties');
select is((select count(*)::int from public.reservation_night_rates where property_id=(select id from rate_other_property)),0,'nightly booking price RLS hides unassigned properties');
select ok(not has_function_privilege('authenticated','public.create_priced_reservation_legacy(uuid,uuid,uuid,text,text,text,date,date,smallint,bigint,text,text)','execute'),'legacy flat-pricing RPC cannot bypass nightly snapshots');
select throws_ok($$select * from rate_hotel h,rate_rooms r,lateral public.get_room_rate_quote(r.id,h.today,h.today+367) q where r.room_number='101'$$,'22023',null,'quote rejects stays beyond the supported limit');

select * from finish();
rollback;
