begin;
select no_plan();
insert into auth.users(id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values ('18000000-0000-4000-8000-000000000001','authenticated','authenticated','supplier-owner@test.local','',now(),'{}','{}',now(),now());
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000001',true);
select set_config('request.jwt.claims','{"sub":"18000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
create temp table sa_ctx(kind text primary key,organization_id uuid,property_id uuid);
insert into sa_ctx select 'a',organization_id,property_id from public.setup_hotel('Supplier accounting tests','Primary test property',null,2,100000);
insert into sa_ctx select 'b',organization_id,gen_random_uuid() from sa_ctx where kind='a';
insert into public.properties(id,organization_id,name) select property_id,organization_id,'Unassigned property' from sa_ctx where kind='b';
insert into public.organizations(id,name,slug) values('28000000-0000-4000-8000-000000000002','Unrelated hotel','supplier-unrelated');
insert into public.properties(id,organization_id,name) values('38000000-0000-4000-8000-000000000002','28000000-0000-4000-8000-000000000002','Other tenant property');
insert into sa_ctx values('c','28000000-0000-4000-8000-000000000002','38000000-0000-4000-8000-000000000002');
create temp table sa_ids(kind text primary key,id uuid);
grant select on sa_ctx to authenticated;
grant select,insert,update on sa_ids to authenticated;
create function pg_temp.sa_prop(k text default 'a') returns uuid language sql as $$select property_id from sa_ctx where kind=k$$;
create function pg_temp.sa_id(k text) returns uuid language sql as $$select id from sa_ids where kind=k$$;
create function pg_temp.sa_dept(c text,k text default 'a') returns uuid language sql as $$select d.id from public.departments d join sa_ctx h on d.property_id=h.property_id where h.kind=k and d.code=c$$;
create function pg_temp.sa_method(k text default 'a') returns uuid language sql as $$select m.id from public.payment_methods m join sa_ctx h on m.property_id=h.property_id where h.kind=k and m.clearing_account_code='1010' limit 1$$;
create function pg_temp.sa_today() returns date language sql as $$select (now() at time zone 'Africa/Lagos')::date$$;
create function pg_temp.sa_bill(n text,a bigint,k text,d date default pg_temp.sa_today()-60) returns uuid language sql as $$select public.post_supplier_bill(pg_temp.sa_prop(),pg_temp.sa_id('supplier'),n,d,d,d+10,'Operating supplies','5010',pg_temp.sa_dept('restaurant'),a,k)$$;

set local role authenticated;
select is((select count(*)::int from public.departments where property_id=pg_temp.sa_prop()),6,'property receives six operational departments');
select is((select count(*)::int from public.accounts a join sa_ctx h on a.organization_id=h.organization_id where h.kind='a' and a.code='2000'),1,'supplier payable account is seeded once');
select lives_ok($$insert into sa_ids values('supplier',public.save_supplier(pg_temp.sa_prop(),null,'Fresh Foods','08000000000','SUPPLIER@TEST.LOCAL','Calabar',true))$$,'owner creates a property supplier');
select is((select email from public.suppliers where id=pg_temp.sa_id('supplier')),'supplier@test.local','supplier email is normalized');
select throws_ok($$select public.save_supplier(pg_temp.sa_prop(),null,'fresh foods',null,null,null,true)$$,'23505',null,'case-insensitive duplicate supplier is rejected');
select lives_ok($$select public.save_supplier(pg_temp.sa_prop(),pg_temp.sa_id('supplier'),'Fresh Foods','08000000001',null,'Calabar',true)$$,'supplier contacts can be updated');
select lives_ok($$insert into sa_ids values('bill',pg_temp.sa_bill(' INV-100 ',100000,'sa-bill-100'))$$,'expense invoice posts as an unpaid bill');
select is((select bill_number from public.supplier_bills where id=pg_temp.sa_id('bill')),'INV-100','invoice number is normalized');
select is(pg_temp.sa_bill('inv-100',100000,'sa-bill-100'),pg_temp.sa_id('bill'),'identical bill retry returns original record');
select throws_ok($$select pg_temp.sa_bill('INV-100',100001,'sa-bill-100')$$,'23505',null,'changed bill retry is rejected');
select throws_ok($$select pg_temp.sa_bill('INV-100',100000,'sa-bill-another-key')$$,'23505',null,'same supplier invoice cannot post under another key');
select is((select count(*)::int from public.journals where source_type='supplier_bill'),1,'duplicate attempts leave one bill journal');
select is((select outstanding_kobo from public.get_supplier_bill_balances(pg_temp.sa_prop(),pg_temp.sa_today()) where bill_id=pg_temp.sa_id('bill')),100000::bigint,'full bill is payable before settlement');
select is((select amount_kobo from public.get_profit_and_loss(pg_temp.sa_prop(),pg_temp.sa_today()-60,pg_temp.sa_today()) where account_code='5010'),100000::bigint,'expense is recognized on bill posting');
select is((select expense_kobo from public.get_department_profit_and_loss(pg_temp.sa_prop(),pg_temp.sa_today()-60,pg_temp.sa_today()) where department_code='restaurant'),100000::bigint,'bill expense retains its department');
select is((select credit_balance_kobo from public.get_trial_balance(pg_temp.sa_prop(),pg_temp.sa_today()) where account_code='2000'),100000::bigint,'trial balance has the unpaid liability');
select is((select count(*)::int from public.get_supplier_bill_balances(pg_temp.sa_prop(),pg_temp.sa_today()-61)),0,'report excludes bills not yet posted');
select lives_ok($$insert into sa_ids values('payment',public.pay_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_method(),pg_temp.sa_today()-40,40000,'BANK-1','sa-payment-100'))$$,'owner records a partial bank settlement');
select is(public.pay_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_method(),pg_temp.sa_today()-40,40000,'BANK-1','sa-payment-100'),pg_temp.sa_id('payment'),'identical payment retry is safe');
select throws_ok($$select public.pay_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_method(),pg_temp.sa_today()-40,40001,'BANK-1','sa-payment-100')$$,'23505',null,'changed payment retry is rejected');
select is((select outstanding_kobo from public.get_supplier_bill_balances(pg_temp.sa_prop(),pg_temp.sa_today()) where bill_id=pg_temp.sa_id('bill')),60000::bigint,'partial payment reduces liability');
select is((select amount_kobo from public.get_profit_and_loss(pg_temp.sa_prop(),pg_temp.sa_today()-60,pg_temp.sa_today()) where account_code='5010'),100000::bigint,'payment does not recognize expense a second time');
select is((select credit_balance_kobo from public.get_trial_balance(pg_temp.sa_prop(),pg_temp.sa_today()) where account_code='2000'),60000::bigint,'subledger agrees with payable account');
select is((select overdue_31_60_kobo from public.get_supplier_payables_summary(pg_temp.sa_prop(),pg_temp.sa_today())),60000::bigint,'payable aging uses due date and outstanding balance');
select throws_ok($$select public.pay_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_method(),pg_temp.sa_today(),60001,null,'sa-payment-overpay')$$,'23514',null,'payment above balance is rejected');
select throws_ok($$select public.void_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_today(),'Incorrect invoice')$$,'23514',null,'bill with active payment cannot be voided');
select lives_ok($$insert into sa_ids values('reversal',public.reverse_supplier_payment(pg_temp.sa_id('payment'),pg_temp.sa_today()-20,'Bank transfer returned'))$$,'payment correction creates a linked reversal');
select is(public.reverse_supplier_payment(pg_temp.sa_id('payment'),pg_temp.sa_today()-20,'Bank transfer returned'),pg_temp.sa_id('reversal'),'same reversal retry returns original correction');
select throws_ok($$select public.reverse_supplier_payment(pg_temp.sa_id('payment'),pg_temp.sa_today()-20,'Different correction')$$,'23505',null,'changed reversal retry is rejected');
select is((select reverses_journal_id from public.journals where id=pg_temp.sa_id('reversal')),(select journal_id from public.supplier_bill_payments where id=pg_temp.sa_id('payment')),'reversal links immutable original payment journal');
select is((select outstanding_kobo from public.get_supplier_bill_balances(pg_temp.sa_prop(),pg_temp.sa_today())),100000::bigint,'reversal restores payable');
select is((select outstanding_kobo from public.get_supplier_bill_balances(pg_temp.sa_prop(),pg_temp.sa_today()-30)),60000::bigint,'future correction leaves historical balance unchanged');
select is((select status from public.get_supplier_payment_history(pg_temp.sa_prop(),pg_temp.sa_today()-30)),'posted','historical payment status reflects correction date');
select is((select status from public.get_supplier_payment_history(pg_temp.sa_prop(),pg_temp.sa_today())),'reversed','current payment history shows reversal');
select throws_ok($$select public.pay_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_method(),pg_temp.sa_today()-50,70000,null,'sa-payment-backdated')$$,'23514',null,'backdated payment cannot overpay an intervening period');
select lives_ok($$insert into sa_ids values('void',public.void_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_today()-10,'Supplier cancelled invoice'))$$,'fully reversed bill can be voided');
select is(public.void_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_today()-10,'Supplier cancelled invoice'),pg_temp.sa_id('void'),'void retry is idempotent');
select throws_ok($$select public.void_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_today()-10,'Different void reason')$$,'23505',null,'changed void retry is rejected');
select is((select reverses_journal_id from public.journals where id=pg_temp.sa_id('void')),(select journal_id from public.supplier_bills where id=pg_temp.sa_id('bill')),'bill void links original expense journal');
select is((select status from public.get_supplier_bill_balances(pg_temp.sa_prop(),pg_temp.sa_today()-15)),'posted','historical bill remains posted before void date');
select is((select outstanding_kobo from public.get_supplier_bill_balances(pg_temp.sa_prop(),pg_temp.sa_today())),0::bigint,'void clears payable today');
select is((select amount_kobo from public.get_profit_and_loss(pg_temp.sa_prop(),pg_temp.sa_today()-60,pg_temp.sa_today()) where account_code='5010'),0::bigint,'void cancels expense once');
select throws_ok($$select public.pay_supplier_bill(pg_temp.sa_id('bill'),pg_temp.sa_method(),pg_temp.sa_today(),10000,null,'sa-payment-voided')$$,'23514',null,'voided bill cannot receive new settlement');
select lives_ok($$insert into sa_ids values('replacement',pg_temp.sa_bill('INV-100',80000,'sa-bill-replacement',pg_temp.sa_today()-5))$$,'corrected invoice number can be reused after void');
select is((select outstanding_kobo from public.get_supplier_payables_summary(pg_temp.sa_prop(),pg_temp.sa_today())),80000::bigint,'only replacement contributes current payable');
select throws_ok($$select public.attach_supplier_bill_receipt(pg_temp.sa_id('replacement'),'incorrect/path')$$,'22023',null,'receipt path must match organization property and bill');
select throws_ok($$select public.attach_supplier_bill_receipt(pg_temp.sa_id('replacement'),(select organization_id::text||'/'||property_id::text||'/'||pg_temp.sa_id('replacement')::text||'/invoice.pdf' from sa_ctx where kind='a'))$$,'P0002',null,'receipt cannot link before upload exists');
reset role;
insert into storage.objects(bucket_id,name) select 'expense-receipts',organization_id::text||'/'||property_id::text||'/'||pg_temp.sa_id('replacement')::text||'/invoice.pdf' from sa_ctx where kind='a';
set local role authenticated;
select lives_ok($$select public.attach_supplier_bill_receipt(pg_temp.sa_id('replacement'),(select organization_id::text||'/'||property_id::text||'/'||pg_temp.sa_id('replacement')::text||'/invoice.pdf' from sa_ctx where kind='a'))$$,'uploaded private invoice can be attached');
select ok((select receipt_path is not null from public.supplier_bills where id=pg_temp.sa_id('replacement')),'receipt metadata persists without changing accounting');
select is((select count(*)::int from public.audit_events where action='supplier_bill_receipt_attached' and entity_id=pg_temp.sa_id('replacement')),1,'invoice attachment records the staff audit event');
select lives_ok($$insert into sa_ids values('settled',public.pay_supplier_bill(pg_temp.sa_id('replacement'),pg_temp.sa_method(),pg_temp.sa_today(),80000,'BANK-2','sa-pay-replacement'))$$,'replacement invoice can be fully settled');
select is((select outstanding_kobo from public.get_supplier_payables_summary(pg_temp.sa_prop(),pg_temp.sa_today())),0::bigint,'fully paid invoice has no unpaid balance');
select is((select count(*)::int from public.audit_events where action='journal_posted'),6,'each new posting and correction records one audit event');
select ok(not has_function_privilege('authenticated','public.post_department_accounting_event(uuid,uuid,text,uuid,date,text,bigint,text,text,text,uuid,uuid)','execute'),'staff cannot invoke private journal helper');
select ok(not has_function_privilege('authenticated','public.post_accounting_event(uuid,uuid,text,uuid,date,text,bigint,text,text,text)','execute'),'legacy journal helper stays private');
reset role;
select throws_ok($$update public.supplier_bills set amount_kobo=1 where id=pg_temp.sa_id('replacement')$$,'23514',null,'posted supplier bill amount is immutable even for admin writes');
select throws_ok($$update public.supplier_bill_payments set amount_kobo=1 where id=pg_temp.sa_id('settled')$$,'23514',null,'posted supplier payment amount is immutable');
select throws_ok($$delete from public.supplier_bills where id=pg_temp.sa_id('bill')$$,'23514',null,'voided bills cannot be deleted');
select throws_ok($$delete from public.supplier_bill_payments where id=pg_temp.sa_id('payment')$$,'23514',null,'reversed payments cannot be deleted');
select throws_ok($$update public.supplier_bills set void_reason=null where id=pg_temp.sa_id('bill')$$,'23514',null,'terminal bill correction reason cannot be removed');
select throws_ok($$update public.supplier_bill_payments set reversal_reason=null where id=pg_temp.sa_id('payment')$$,'23514',null,'terminal payment correction reason cannot be removed');
select throws_ok($$update public.journals set department_id=pg_temp.sa_dept('bar') where id=(select journal_id from public.supplier_bills where id=pg_temp.sa_id('replacement'))$$,'23514',null,'posted journal department cannot be reclassified in place');
-- IDs for foreign-property references must be retained before property RLS hides them.
insert into sa_ids values('foreign-dept',pg_temp.sa_dept('restaurant','b')),('foreign-method',pg_temp.sa_method('b'));
insert into public.suppliers(id,organization_id,property_id,name,created_by) select gen_random_uuid(),organization_id,property_id,'Foreign supplier',auth.uid() from sa_ctx where kind='b';
insert into sa_ids select 'foreign-supplier',id from public.suppliers where property_id=pg_temp.sa_prop('b');
set local role authenticated;
select throws_ok($$select public.post_supplier_bill(pg_temp.sa_prop(),pg_temp.sa_id('foreign-supplier'),'OTHER',pg_temp.sa_today(),pg_temp.sa_today(),pg_temp.sa_today(),'Foreign supplier','5010',pg_temp.sa_dept('restaurant'),10000,'sa-foreign-supplier')$$,'22023',null,'bill rejects supplier from another property');
select throws_ok($$select public.post_supplier_bill(pg_temp.sa_prop(),pg_temp.sa_id('supplier'),'OTHER',pg_temp.sa_today(),pg_temp.sa_today(),pg_temp.sa_today(),'Foreign department','5010',pg_temp.sa_id('foreign-dept'),10000,'sa-foreign-department')$$,'22023',null,'bill rejects department from another property');
select throws_ok($$select public.pay_supplier_bill(pg_temp.sa_id('replacement'),pg_temp.sa_id('foreign-method'),pg_temp.sa_today(),1,null,'sa-foreign-method')$$,'22023',null,'settlement rejects payment method from another property');
select throws_ok($$select * from public.get_supplier_bill_balances(pg_temp.sa_prop('c'),pg_temp.sa_today())$$,'42501',null,'supplier report rejects other tenant');
select throws_ok($$select public.save_supplier(pg_temp.sa_prop('c'),null,'Unauthorized supplier',null,null,null,true)$$,'42501',null,'supplier write rejects other tenant');
-- An assigned accountant may work in property A, while B audit amounts remain hidden.
reset role;
update public.organization_memberships set role='accountant',all_properties=false where user_id=auth.uid();
insert into public.membership_properties(organization_id,user_id,property_id) select organization_id,auth.uid(),property_id from sa_ctx where kind='a';
insert into public.audit_events(organization_id,property_id,actor_user_id,action,entity_type,entity_id,after_data) select organization_id,property_id,auth.uid(),'journal_posted','journal',gen_random_uuid(),'{"amount_kobo":999999}' from sa_ctx where kind='b';
set local role authenticated;
select is((select count(*)::int from public.suppliers),1,'accountant sees only assigned property suppliers');
select is((select count(*)::int from public.audit_events where property_id=pg_temp.sa_prop('b')),0,'accountant cannot read unassigned property financial audit');
select is((select count(*)::int from public.departments),6,'department list respects property assignment');
select throws_ok($$select * from public.get_supplier_payables_summary(pg_temp.sa_prop('b'),pg_temp.sa_today())$$,'42501',null,'accountant cannot report unassigned property');
select lives_ok($$insert into sa_ids values('accountant-bill',pg_temp.sa_bill('ACC-1',20000,'sa-accountant-bill',pg_temp.sa_today()))$$,'accountant can record assigned-property invoice');
select lives_ok($$insert into sa_ids values('accountant-payment',public.pay_supplier_bill(pg_temp.sa_id('accountant-bill'),pg_temp.sa_method(),pg_temp.sa_today(),10000,null,'sa-accountant-payment'))$$,'accountant can pay assigned-property bill');
reset role;
update public.organization_memberships set role='manager' where user_id=auth.uid();
set local role authenticated;
select lives_ok($$insert into sa_ids values('manager-bill',pg_temp.sa_bill('MGR-1',30000,'sa-manager-bill',pg_temp.sa_today()))$$,'manager can record supplier invoice');
select throws_ok($$select public.pay_supplier_bill(pg_temp.sa_id('manager-bill'),pg_temp.sa_method(),pg_temp.sa_today(),10000,null,'sa-manager-payment')$$,'42501',null,'manager cannot settle supplier bill');
select throws_ok($$select public.void_supplier_bill(pg_temp.sa_id('manager-bill'),pg_temp.sa_today(),'Manager cancellation')$$,'42501',null,'manager cannot void supplier bill');
select throws_ok($$select public.reverse_supplier_payment(pg_temp.sa_id('accountant-payment'),pg_temp.sa_today(),'Manager reversal')$$,'42501',null,'manager cannot reverse supplier payment');
reset role;
update public.organization_memberships set role='front_desk' where user_id=auth.uid();
set local role authenticated;
select is((select count(*)::int from public.suppliers),0,'front desk cannot read supplier contacts');
select is((select count(*)::int from public.supplier_bills),0,'front desk cannot read supplier invoice records');
select is((select count(*)::int from public.supplier_bill_payments),0,'front desk cannot read supplier payments');
select throws_ok($$select * from public.get_supplier_payables_summary(pg_temp.sa_prop(),pg_temp.sa_today())$$,'42501',null,'front desk cannot report payables');
select throws_ok($$select pg_temp.sa_bill('FD-1',1000,'sa-frontdesk-bill',pg_temp.sa_today())$$,'42501',null,'front desk cannot record supplier invoice');
select throws_ok($$select public.save_supplier(pg_temp.sa_prop(),null,'Front desk supplier',null,null,null,true)$$,'42501',null,'front desk cannot create supplier');
reset role;
update public.organization_memberships set role='housekeeping' where user_id=auth.uid();
set local role authenticated;
select is((select count(*)::int from public.supplier_bills),0,'housekeeper cannot read supplier invoice records');
select throws_ok($$select * from public.get_supplier_payment_history(pg_temp.sa_prop(),pg_temp.sa_today())$$,'42501',null,'housekeeper cannot report supplier payments');
reset role;
update public.organization_memberships set role='owner',all_properties=true where user_id=auth.uid();
set local role authenticated;
select is((select sum(debit_balance_kobo-credit_balance_kobo)::bigint from public.get_trial_balance(pg_temp.sa_prop(),pg_temp.sa_today())),0::bigint,'all supplier events and corrections leave trial balance balanced');
select is((select credit_balance_kobo from public.get_trial_balance(pg_temp.sa_prop(),pg_temp.sa_today()) where account_code='2000'),(select outstanding_kobo from public.get_supplier_payables_summary(pg_temp.sa_prop(),pg_temp.sa_today())),'payables report reconciles to liability after all role workflows');
select * from finish();
rollback;
