-- Run on a disposable migrated database. All synthetic records roll back.
begin;
create function pg_temp.assert_true(v boolean,message text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'FAIL: %',message; end if; raise notice 'PASS: %',message; end$$;
create function pg_temp.expect_failure(sql text,expected_state text,message text) returns void language plpgsql as $$
begin
  begin execute sql;
  exception when others then
    if expected_state is not null and sqlstate<>expected_state then raise exception 'FAIL: % (unexpected state %: %)',message,sqlstate,sqlerrm; end if;
    raise notice 'PASS: %',message;return;
  end;
  raise exception 'FAIL: % (operation unexpectedly succeeded)',message;
end$$;
insert into auth.users(id,email) values('16000000-0000-4000-8000-000000000001','configuration-owner@test.local'),('16000000-0000-4000-8000-000000000002','configuration-staff@test.local');
select set_config('request.jwt.claim.sub','16000000-0000-4000-8000-000000000001',true);
create temp table config_hotel as select * from public.setup_hotel('Configuration tests','Property A',null,2,100000);
create temp table config_other as select public.create_property(organization_id,'Property B',null,1,100000) as id from config_hotel;
create temp table config_ids(kind text primary key,id uuid);
grant select on config_hotel,config_other to authenticated;
grant select,insert on config_ids to authenticated;
set local role authenticated;
select pg_temp.assert_true((select count(*)>0 from public.property_floors f join config_hotel h on h.property_id=f.property_id),'onboarding automatically registers existing floors');
insert into config_ids select 'floor',public.save_property_configuration(property_id,'floor',null,'{"name":"Second Floor"}') from config_hotel;
insert into config_ids select 'type',public.save_property_configuration(property_id,'room_type',null,'{"name":"Suite","base_rate_kobo":7000000,"max_occupancy":4,"active":true}') from config_hotel;
insert into config_ids select 'room',public.save_property_configuration(h.property_id,'room',null,jsonb_build_object('room_number','301','room_type_id',t.id,'floor_label','Second Floor','active',true)) from config_hotel h,config_ids t where t.kind='type';
select pg_temp.assert_true((select housekeeping_status='dirty' from public.rooms where id=(select id from config_ids where kind='room')),'physical rooms are immediately operational and start dirty');
select pg_temp.expect_failure($q$select public.save_property_configuration((select property_id from config_hotel),'room',null,jsonb_build_object('room_number','399','room_type_id',(select room_type_id from public.rooms where property_id=(select id from config_other) limit 1),'active',true))$q$,null,'room types cannot cross properties');
select pg_temp.expect_failure($q$select public.save_property_configuration((select property_id from config_hotel),null,null,'{}')$q$,null,'unknown configuration kinds are rejected');
select public.save_property_configuration(h.property_id,'floor',f.id,'{"name":"Upper Floor"}') from config_hotel h,config_ids f where f.kind='floor';
select pg_temp.assert_true((select floor_label='Upper Floor' from public.rooms where id=(select id from config_ids where kind='room')),'renaming floors preserves room assignments');
insert into config_ids select 'booking',public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Configuration guest',null,null,current_date+1,current_date+3,1::smallint,null) from config_hotel h,config_ids r where r.kind='room';
select pg_temp.expect_failure($q$select public.save_property_configuration(h.property_id,'room',r.id,jsonb_build_object('room_number','301','room_type_id',t.id,'floor_label','Upper Floor','active',false)) from config_hotel h,config_ids r,config_ids t where r.kind='room' and t.kind='type'$q$,null,'reserved rooms cannot be deactivated');
select public.save_property_configuration(h.property_id,'room_type',t.id,'{"name":"Executive Suite","base_rate_kobo":1,"max_occupancy":4,"active":true}') from config_hotel h,config_ids t where t.kind='type';
select pg_temp.assert_true((select base_rate_kobo=7000000 from public.room_types where id=(select id from config_ids where kind='type')),'configuration edits cannot bypass the audited rate workflow');
select pg_temp.assert_true((select sum(charged_rate_kobo)=14000000 from public.reservation_night_rates where reservation_id=(select id from config_ids where kind='booking')),'configuration changes preserve agreed nightly booking prices');
insert into config_ids select 'tax',public.save_property_configuration(property_id,'tax',null,'{"name":"Service levy","rate_basis_points":500,"active":true}') from config_hotel;
select pg_temp.assert_true((select rate_basis_points=500 from public.property_tax_rules where id=(select id from config_ids where kind='tax')),'tax setup persists without adding unsolicited charges');
insert into config_ids select 'method',public.save_property_configuration(property_id,'payment_method',null,'{"name":"Hotel cash","clearing_account_code":"1000","active":true}') from config_hotel;
select pg_temp.expect_failure($q$select public.save_property_configuration(h.property_id,'payment_method',m.id,'{"name":"Hotel cash","clearing_account_code":"1010","active":true}') from config_hotel h,config_ids m where m.kind='method'$q$,null,'existing payment account mappings cannot be rewritten');
insert into config_ids select 'stock',public.save_stock_item(property_id,'Water','bottle',5) from config_hotel;
insert into config_ids select 'receipt',public.record_stock_movement(id,10,'Opening count','config-opening') from config_ids where kind='stock';
select pg_temp.assert_true((select public.record_stock_movement(id,10,'Opening count','config-opening')=(select id from config_ids where kind='receipt') from config_ids where kind='stock'),'repeated stock movement submissions return the original receipt');
select public.record_stock_movement(id,-3,'Guest consumption','config-issue') from config_ids where kind='stock';
select pg_temp.assert_true((select on_hand=7 from public.stock_balances where id=(select id from config_ids where kind='stock')),'stock balance derives from receipts and issues');
select pg_temp.expect_failure($q$select public.record_stock_movement(id,-8,'Excess consumption','config-overdraw') from config_ids where kind='stock'$q$,null,'stock cannot be overdrawn');
select pg_temp.expect_failure($q$select public.record_stock_movement(id,9,'Opening count','config-opening') from config_ids where kind='stock'$q$,null,'an idempotency key cannot hide a different quantity');
select pg_temp.expect_failure($q$insert into public.stock_movements(organization_id,property_id,item_id,quantity,reason,idempotency_key,created_by) select h.organization_id,h.property_id,i.id,1,'Bypass test','config-bypass',auth.uid() from config_hotel h,config_ids i where kind='stock'$q$,'42501','clients cannot bypass stock RPCs');
reset role;
select pg_temp.expect_failure($q$update public.stock_movements set quantity=100 where id=(select id from config_ids where kind='receipt')$q$,null,'stored stock movements are immutable');
select pg_temp.assert_true((select count(*)>=10 from public.audit_events where action in ('configuration_saved','stock_item_created','stock_movement_recorded')),'configuration and stock mutations are audited');
insert into public.organization_memberships(organization_id,user_id,role,all_properties) select organization_id,'16000000-0000-4000-8000-000000000002','accountant',false from config_hotel;
insert into public.membership_properties(organization_id,user_id,property_id) select organization_id,'16000000-0000-4000-8000-000000000002',property_id from config_hotel;
select set_config('request.jwt.claim.sub','16000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select pg_temp.assert_true((select on_hand=7 from public.stock_balances where id=(select id from config_ids where kind='stock')),'assigned accountant can read stock balances');
select pg_temp.expect_failure($q$select public.save_property_configuration((select property_id from config_hotel),'floor',null,'{"name":"Forbidden"}')$q$,'42501','accountants cannot configure physical rooms');
select pg_temp.expect_failure($q$select public.save_stock_item((select id from config_other),'Hidden stock','pack',1)$q$,'42501','stock mutations cannot cross property grants');
reset role;
update public.organization_memberships set role='front_desk' where user_id='16000000-0000-4000-8000-000000000002';
set local role authenticated;
select pg_temp.assert_true((select count(*)=0 from public.stock_balances),'stock RLS hides inventory from front desk');
select pg_temp.expect_failure($q$select public.record_stock_movement(id,1,'Unauthorized receive','config-denied') from config_ids where kind='stock'$q$,'42501','front desk cannot record stock movements');
reset role;
update public.organization_memberships set role='manager' where user_id='16000000-0000-4000-8000-000000000002';
set local role authenticated;
select pg_temp.expect_failure($q$select public.save_property_configuration((select id from config_other),'floor',null,'{"name":"Forbidden"}')$q$,'42501','scoped manager cannot configure an unassigned property');
reset role;
update public.organization_memberships set role='housekeeping' where user_id='16000000-0000-4000-8000-000000000002';
set local role authenticated;
select pg_temp.assert_true((select count(*)=0 from public.stock_balances),'housekeeping cannot read stock inventory');
select pg_temp.expect_failure($q$select public.save_property_configuration((select property_id from config_hotel),'floor',null,'{"name":"Housekeeping forbidden"}')$q$,'42501','housekeeping cannot configure rooms');
select pg_temp.expect_failure($q$select public.create_priced_reservation(h.organization_id,h.property_id,r.id,'Forbidden booking',null,null,current_date+10,current_date+11,1::smallint,null) from config_hotel h,public.rooms r where r.property_id=h.property_id and r.room_number='101'$q$,'42501','housekeeping cannot create reservations');
select public.update_room_housekeeping_status(r.id,'clean') from public.rooms r,config_hotel h where r.property_id=h.property_id and r.room_number='101';
select pg_temp.assert_true((select housekeeping_status='clean' from public.rooms r,config_hotel h where r.property_id=h.property_id and r.room_number='101'),'housekeeping can mark assigned rooms clean');
reset role;
update public.organization_memberships set role='manager' where user_id='16000000-0000-4000-8000-000000000002';
set local role authenticated;
select public.save_property_configuration((select property_id from config_hotel),'floor',null,'{"name":"Manager allowed"}');
select pg_temp.assert_true((select count(*)=1 from public.property_floors where name='Manager allowed'),'manager can configure the assigned property');
reset role;
update public.organization_memberships set role='accountant' where user_id='16000000-0000-4000-8000-000000000002';
set local role authenticated;
select public.record_stock_movement(id,1,'Accountant adjustment','config-accountant') from config_ids where kind='stock';
select pg_temp.assert_true((select on_hand=8 from public.stock_balances where id=(select id from config_ids where kind='stock')),'accountant can record stock adjustments in the assigned property');
reset role;
rollback;
