begin;
create function pg_temp.assert_true(v boolean,message text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'FAIL: %',message;end if;raise notice 'PASS: %',message;end$$;
create function pg_temp.expect_failure(sql text,message text) returns void language plpgsql as $$begin begin execute sql;exception when others then raise notice 'PASS: %',message;return;end;raise exception 'FAIL: %',message;end$$;
insert into auth.users(id,email) values('18000000-0000-4000-8000-000000000001','shift-owner@test.local'),('18000000-0000-4000-8000-000000000002','shift-desk@test.local');
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000001',true);
create temp table shift_hotel as select * from public.setup_hotel('Shift tests','Shift property',null,1,10000);
create temp table shift_other as select public.create_property(organization_id,'Other property',null,1,10000) id from shift_hotel;
insert into public.organization_memberships(organization_id,user_id,role,active,all_properties) select organization_id,'18000000-0000-4000-8000-000000000002','front_desk',true,false from shift_hotel;
insert into public.membership_properties(organization_id,user_id,property_id) select organization_id,'18000000-0000-4000-8000-000000000002',property_id from shift_hotel;
create temp table shift_ids(kind text primary key,id uuid);
grant select on shift_hotel,shift_other to authenticated;grant select,insert on shift_ids to authenticated;
set local role authenticated;
select public.save_staff_name(organization_id,'Test Owner') from shift_hotel;
select pg_temp.assert_true((select full_name='Test Owner' from public.get_staff_directory((select organization_id from shift_hotel)) where user_id=auth.uid()),'owner name is saved in staff directory');
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000002',true);
select pg_temp.expect_failure($q$select public.start_staff_shift(property_id) from shift_hotel$q$,'unnamed staff cannot start a shift');
select public.save_staff_name(organization_id,'Test Receptionist') from shift_hotel;
select pg_temp.expect_failure($q$select public.save_staff_name(organization_id,'Impersonation','18000000-0000-4000-8000-000000000001') from shift_hotel$q$,'front desk cannot rename another employee');
select pg_temp.expect_failure($q$select public.start_staff_shift(id) from shift_other$q$,'unassigned property shift is denied');
insert into shift_ids select 'desk',public.start_staff_shift(property_id) from shift_hotel;
select pg_temp.assert_true((select public.start_staff_shift(property_id)=(select id from shift_ids where kind='desk') from shift_hotel),'repeated start returns the same active shift');
select pg_temp.assert_true((select staff_name='Test Receptionist' and staff_role='front_desk' from public.staff_shifts where id=(select id from shift_ids where kind='desk')),'shift preserves staff name and role snapshot');
select public.update_room_housekeeping_status(id,'clean') from public.rooms where property_id=(select property_id from shift_hotel);
select pg_temp.assert_true((select (public.staff_handover_summary(property_id)->>'dirty_rooms')::int=0 from shift_hotel),'handover uses live room readiness');
select pg_temp.expect_failure($q$select public.end_staff_shift((select id from shift_ids where kind='desk'),'')$q$,'handover note is required');
insert into shift_ids select 'cashier',public.open_cashier_shift(property_id,0,'test-staff-cashier') from shift_hotel;
select pg_temp.expect_failure($q$select public.end_staff_shift((select id from shift_ids where kind='desk'),'Test complete')$q$,'unreconciled cashier shift blocks staff checkout');
select public.request_close_cashier_shift(id,0,null) from shift_ids where kind='cashier';
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000001',true);
select pg_temp.expect_failure($q$select public.end_staff_shift((select id from shift_ids where kind='desk'),'Owner takeover')$q$,'owner cannot end someone else’s shift');
select pg_temp.assert_true((select count(*)=1 from public.staff_shifts where property_id=(select property_id from shift_hotel)),'owner can read property team shifts');
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000002',true);
select public.end_staff_shift(id,'TEST handover completed; no real shift') from shift_ids where kind='desk';
select public.end_staff_shift(id,'Retry does not replace original handover') from shift_ids where kind='desk';
select pg_temp.assert_true((select ended_at is not null and handover_note='TEST handover completed; no real shift' and handover_summary->>'in_house'='0' from public.staff_shifts where id=(select id from shift_ids where kind='desk')),'end is idempotent and preserves handover snapshot');
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000001',true);
insert into shift_ids select 'owner',public.start_staff_shift(property_id) from shift_hotel;
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000002',true);
select pg_temp.assert_true((select count(*)=1 from public.staff_shifts where property_id=(select property_id from shift_hotel)),'front desk history does not expose another employee’s private shift');
select pg_temp.assert_true((select count(*)=1 from public.get_shift_handovers((select property_id from shift_hotel))),'incoming front desk can read completed front desk handovers');
select pg_temp.assert_true((select not (handover_summary ? 'my_cash_received_kobo') from public.get_shift_handovers((select property_id from shift_hotel)) limit 1),'incoming staff do not receive another cashier’s receipt totals');
select pg_temp.expect_failure($q$select public.get_shift_handovers(id) from shift_other$q$,'unassigned-property handovers are denied');
reset role;
select pg_temp.assert_true((select count(*)>=2 from public.audit_events where staff_shift_id=(select id from shift_ids where kind='desk')),'actions and closing audit retain their shift attribution');
-- Exercise named invitation acceptance without persistent auth records.
insert into auth.users(id,email) values('18000000-0000-4000-8000-000000000003','shift-invited@test.local');
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000001',true);
create temp table shift_invite(token text);grant select,insert on shift_invite to authenticated;
set local role authenticated;
insert into shift_invite select public.create_named_team_invitation(organization_id,property_id,'shift-invited@test.local','housekeeping','Test Cleaner') from shift_hotel;
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000003',true);
select set_config('request.jwt.claims','{"sub":"18000000-0000-4000-8000-000000000003","email":"shift-invited@test.local"}',true);
select public.accept_team_invitation(token) from shift_invite;
select pg_temp.assert_true((select full_name='Test Cleaner' from public.organization_memberships where user_id=auth.uid() and organization_id=(select organization_id from shift_hotel)),'accepted invitation preserves the supplied full name');
select pg_temp.assert_true((select count(*)=0 from public.get_shift_handovers((select property_id from shift_hotel))),'housekeeping does not receive front desk handover notes');
select pg_temp.assert_true((select not (public.staff_handover_summary(property_id) ? 'outstanding_kobo') from shift_hotel),'housekeeping handover excludes money');
reset role;
rollback;
