begin;
create function pg_temp.assert_true(v boolean,message text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'FAIL: %',message; end if; raise notice 'PASS: %',message; end$$;
create function pg_temp.expect_failure(sql text,message text) returns void language plpgsql as $$begin begin execute sql; exception when others then raise notice 'PASS: %',message;return;end;raise exception 'FAIL: %',message;end$$;
insert into auth.users(id,email) values('17000000-0000-4000-8000-000000000001','stay-acceptance@test.local');
select set_config('request.jwt.claim.sub','17000000-0000-4000-8000-000000000001',true);
create temp table stay_hotel as select * from public.setup_hotel('TEST rollback acceptance','TEST overnight property',null,1,10000);
create temp table stay_ids(kind text primary key,id uuid);
grant select on stay_hotel to authenticated;grant select,insert on stay_ids to authenticated;
set local role authenticated;
select public.update_room_housekeeping_status(r.id,'clean') from public.rooms r,stay_hotel h where r.property_id=h.property_id;
insert into stay_ids select 'booking',public.create_priced_reservation(h.organization_id,h.property_id,r.id,'TEST overnight guest',null,null,(now() at time zone 'Africa/Lagos')::date-1,(now() at time zone 'Africa/Lagos')::date+1,1::smallint,null) from stay_hotel h,public.rooms r where r.property_id=h.property_id;
insert into stay_ids select 'folio',public.check_in_reservation(id) from stay_ids where kind='booking';
select pg_temp.assert_true((select status='checked_in' from public.reservations where id=(select id from stay_ids where kind='booking')),'hosted booking checks in with a ready room');
select pg_temp.assert_true((select public.post_due_room_nights(id)=1 from stay_ids where kind='booking'),'one completed overnight room charge posts');
select pg_temp.assert_true((select public.post_due_room_nights(id)=0 from stay_ids where kind='booking'),'repeated room-night posting is idempotent');
insert into stay_ids select 'charge',public.post_department_folio_charge(f.id,'TEST synthetic service',2500,'test-overnight-extra',d.id) from stay_ids f,public.departments d,stay_hotel h where f.kind='folio' and d.property_id=h.property_id and d.code='services';
select pg_temp.assert_true((select sum(total_amount_kobo)=12500 from public.folio_items where folio_id=(select id from stay_ids where kind='folio')),'folio reconciles accommodation and extras');
select pg_temp.expect_failure($q$select public.early_check_out_reservation(id) from stay_ids where kind='booking'$q$,'checkout rejects an unpaid balance');
insert into stay_ids select 'payment',public.record_folio_payment(f.id,m.id,12500,'TEST no actual transfer','test-overnight-payment') from stay_ids f,public.payment_methods m,stay_hotel h where f.kind='folio' and m.property_id=h.property_id and m.clearing_account_code='1000';
select pg_temp.assert_true((select public.record_folio_payment(f.id,m.id,12500,'TEST no actual transfer','test-overnight-payment')=(select id from stay_ids where kind='payment') from stay_ids f,public.payment_methods m,stay_hotel h where f.kind='folio' and m.property_id=h.property_id and m.clearing_account_code='1000'),'payment retry does not create a duplicate receipt');
select pg_temp.assert_true((select sum(total_amount_kobo)=0 from public.folio_items where folio_id=(select id from stay_ids where kind='folio')),'payment settles the entire folio');
select public.early_check_out_reservation(id) from stay_ids where kind='booking';
select pg_temp.assert_true((select status='checked_out' and actual_departure_date=(now() at time zone 'Africa/Lagos')::date from public.reservations where id=(select id from stay_ids where kind='booking')),'early checkout records the property-local departure date');
select pg_temp.assert_true((select status='closed' from public.folios where id=(select id from stay_ids where kind='folio')),'checkout closes the folio');
select pg_temp.assert_true((select housekeeping_status='dirty' from public.rooms r,stay_hotel h where r.property_id=h.property_id),'checkout returns the room to the cleaning queue');
select pg_temp.assert_true((select count(*)=0 from (select j.id from public.journals j join public.journal_lines l on l.journal_id=j.id where j.property_id=(select property_id from stay_hotel) group by j.id having sum(l.debit_kobo)<>sum(l.credit_kobo)) bad),'hosted lifecycle leaves every journal balanced');
select pg_temp.assert_true((select room_revenue_kobo=10000 and other_revenue_kobo=2500 and payments_kobo=12500 and outstanding_kobo=0 from public.get_property_financial_summary((select property_id from stay_hotel),(now() at time zone 'Africa/Lagos')::date-1,(now() at time zone 'Africa/Lagos')::date)),'financial summary agrees with completed nights, extras and collected payment');
reset role;
rollback;
select 'rolled_back',count(*) from auth.users where id='17000000-0000-4000-8000-000000000001';
